name: Hello

on:
  push:
    branches: [main]

jobs:
  greet: 
    runs-on: ubuntu-latest
    steps:
      - name: sayhello
        run: echo "Hi"

      - name: saybye
        run: echo "bye"

  repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: show repo name
       run: echo "the repo name is ${{ github.event.repo.name }}"







