name: Hello

on:
  push:
    branches: [main]

jobs:
  greet: 
    runs-on: ubuntu-latest
    steps:
      - name: sayhello
        run: echo "hello dosto"

      - name: saybye
        run: echo "bye"







